-- Create the candidates table
CREATE TABLE public.candidates (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  image text NULL,
  konsulat text NULL,
  visi text NULL,
  misi text NULL,
  votes integer NOT NULL DEFAULT 0,
  CONSTRAINT candidates_pkey PRIMARY KEY (id)
);

-- Add some sample data
INSERT INTO public.candidates (name, image, konsulat, visi, misi, votes)
VALUES
  ('Budi Santoso', 'https://i.pravatar.cc/300?u=budi', 'Konsulat Jenderal New York', 'Mewujudkan komunitas Indonesia yang lebih erat dan saling mendukung di New York.', '1. Mengadakan acara budaya bulanan. 2. Membuat platform online untuk bantuan sesama warga. 3. Bekerja sama dengan bisnis lokal untuk keuntungan komunitas.', 25),
  ('Citra Lestari', 'https://i.pravatar.cc/300?u=citra', 'Konsulat Jenderal Los Angeles', 'Memperkuat citra positif Indonesia di mata dunia melalui diplomasi budaya dan ekonomi.', '1. Festival film Indonesia tahunan. 2. Misi dagang untuk produk UKM Indonesia. 3. Program pertukaran pemuda.', 42),
  ('Agus Wijaya', 'https://i.pravatar.cc/300?u=agus', 'Konsulat Jenderal Houston', 'Fokus pada perlindungan dan pelayanan WNI di wilayah kerja.', '1. Digitalisasi layanan konsuler. 2. Hotline 24/7 untuk keadaan darurat. 3. Bantuan hukum pro-bono bagi WNI yang membutuhkan.', 18);

-- 1. Enable Row Level Security (RLS)
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;

-- 2. Create a policy for public read access
CREATE POLICY "Allow public read access"
ON public.candidates
FOR SELECT
USING (true);

-- 3. Create a policy to allow updates to the votes column
-- WARNING: This policy allows any anonymous user to update the vote count.
-- For a real application, you should restrict this to authenticated users
-- and implement a mechanism to prevent multiple votes from the same user.
CREATE POLICY "Allow anonymous updates to votes"
ON public.candidates
FOR UPDATE
USING (true)
WITH CHECK (true);
